import { useState } from 'react';
import ScreenHeading from '../components/ScreenHeading';
import { useMockData } from '../hooks/useMockData';
import { minutes, shiftDate, taskEnd, todayInZone, weekDates, WEEKDAYS } from '../services/mockData';
const formatDate = (date: string, options: Intl.DateTimeFormatOptions) => new Intl.DateTimeFormat('en-US',{...options,timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
export default function Calendar() {
  const { tasks, settings } = useMockData();
  const today = todayInZone(settings.timeZone);
  const [offset, setOffset] = useState(0);
  const dates = weekDates(shiftDate(today, offset * 7));
  return <><ScreenHeading title="Make space for your week." description="Your tasks and available hours, together in one view." action={<a className="button" href="#/tasks">Manage tasks</a>} /><section className="card calendar-toolbar"><div><h2>{formatDate(dates[0],{month:'short',day:'numeric',year:'numeric'})} – {formatDate(dates[6],{month:'short',day:'numeric',year:'numeric'})}</h2><p className="muted">{settings.timeZone} · <a className="text-link" href="#/settings">Edit available hours</a></p></div><div className="week-controls"><button className="button secondary" aria-label="Previous week" onClick={()=>setOffset(offset-1)}>←</button><button className="button secondary" onClick={()=>setOffset(0)}>This week</button><button className="button secondary" aria-label="Next week" onClick={()=>setOffset(offset+1)}>→</button></div></section><p className="calendar-help muted">Green shows your available window. Purple shows timed tasks; tasks without a time appear separately. Tasks are placed manually, not automatically scheduled.</p>
    <div className="calendar-grid">{dates.map((date,index)=>{const hours=settings.availability[WEEKDAYS[index]];const daily=tasks.filter(t=>t.date===date).sort((a,b)=>a.startTime.localeCompare(b.startTime));const timed=daily.filter(t=>t.startTime);const untimed=daily.filter(t=>!t.startTime);return <section className={`card calendar-day ${date===today?'is-today':''}`} key={date} aria-label={`${WEEKDAYS[index]} ${date}`}><div className="calendar-date"><h2>{WEEKDAYS[index]}</h2><span>{formatDate(date,{month:'short',day:'numeric'})}</span>{date===today && <span className="today-label">Today</span>}</div><div className={`availability-block ${hours.enabled?'':'unavailable'}`}><strong>{hours.enabled?`${hours.start} – ${hours.end}`:'Unavailable'}</strong><span>{hours.enabled?'Available time':'No available hours'}</span></div><h3 className="calendar-group-title">Timed tasks</h3>{!timed.length && <p className="calendar-empty">No timed tasks</p>}{timed.map(task=>{const outside=!hours.enabled || minutes(task.startTime)<minutes(hours.start) || minutes(task.startTime)+task.duration>minutes(hours.end);const overlap=!task.completed && timed.some(other=>other.id!==task.id && !other.completed && minutes(other.startTime)<minutes(task.startTime)+task.duration && minutes(task.startTime)<minutes(other.startTime)+other.duration);return <a href="#/tasks" className={`calendar-task ${task.completed?'is-complete':''}`} key={task.id}><span>{task.startTime} – {taskEnd(task)}</span><strong>{task.title}</strong><small>{task.completed?'Completed':`${task.duration} min · ${task.priority}`}</small>{outside && <small className="calendar-warning">Outside available hours</small>}{overlap && <small className="calendar-warning">Overlaps another task</small>}{settings.reminders.enabled && !task.completed && <small>Reminder preference: {settings.reminders.minutesBefore} min before (mock)</small>}</a>;})}{untimed.length>0 && <><h3 className="calendar-group-title">No time assigned</h3>{untimed.map(task=><a className={`calendar-task untimed ${task.completed?'is-complete':''}`} href="#/tasks" key={task.id}><strong>{task.title}</strong><small>{task.completed?'Completed':`${task.duration} min · ${task.priority}`}</small></a>)}</>}</section>;})}</div></>;
}
