import { useState, type FormEvent } from 'react';
import ScreenHeading from '../components/ScreenHeading';
import { useMockData } from '../hooks/useMockData';
import { mockDataService, timeZones, WEEKDAYS, type Availability, type Weekday } from '../services/mockData';
export default function Settings() {
  const { settings } = useMockData();
  const [draft, setDraft] = useState(() => structuredClone(settings));
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const dirty = JSON.stringify(draft) !== JSON.stringify(settings);
  function updateDay(day: Weekday, patch: Partial<Availability>) { setDraft({...draft,availability:{...draft.availability,[day]:{...draft.availability[day],...patch}}}); setMessage(''); }
  function save(event: FormEvent) { event.preventDefault(); try { mockDataService.saveSettings(draft); setMessage('Settings saved in this browser. Your calendar is up to date.'); setError(''); } catch(e) { setError((e as Error).message); setMessage(''); } }
  return <><ScreenHeading title="Planning, on your terms." description="Give each day a rhythm that works for you." /><form className="workspace-form" onSubmit={save}>
    <section className="card settings-section"><h2>Available hours by day</h2><p className="muted">Choose one time window for each day. Turn off days when you’re unavailable.</p><div className="availability-list">{WEEKDAYS.map(day => { const hours = draft.availability[day]; return <fieldset className="availability-row" key={day}><legend className="sr-only">{day} availability</legend><label className="day-toggle"><input type="checkbox" checked={hours.enabled} onChange={e=>updateDay(day,{enabled:e.target.checked})}/>{day}</label><div className="day-hours"><label><span className="sr-only">{day} start time</span><input type="time" required disabled={!hours.enabled} value={hours.start} onChange={e=>updateDay(day,{start:e.target.value})}/></label><span>to</span><label><span className="sr-only">{day} end time</span><input type="time" required disabled={!hours.enabled} value={hours.end} onChange={e=>updateDay(day,{end:e.target.value})}/></label></div><span className="day-status">{hours.enabled ? 'Available' : 'Unavailable'}</span></fieldset>; })}</div></section>
    <section className="card settings-section"><h2>Time zone</h2><p className="muted">Availability and task times use this zone. Changing it keeps your entered clock times; it does not convert existing tasks.</p><label className="timezone-field">Planning time zone<select value={draft.timeZone} onChange={e=>{setDraft({...draft,timeZone:e.target.value});setMessage('');}}>{[...new Set([...timeZones,draft.timeZone])].sort().map(zone=><option key={zone} value={zone}>{zone}</option>)}</select></label></section>
    <section className="card settings-section"><h2>Optional reminders</h2><label className="checkbox-label"><input type="checkbox" checked={draft.reminders.enabled} onChange={e=>{setDraft({...draft,reminders:{...draft.reminders,enabled:e.target.checked}});setMessage('');}}/>Enable task reminders</label><label className="timezone-field">Remind me before a timed task<select disabled={!draft.reminders.enabled} value={draft.reminders.minutesBefore} onChange={e=>{setDraft({...draft,reminders:{...draft.reminders,minutesBefore:Number(e.target.value)}});setMessage('');}}>{[5,10,15,30,60].map(value=><option key={value} value={value}>{value} minutes before</option>)}</select></label><p className="muted">Mock preference only: no email, push, or browser notifications are sent. Tasks without a start time have no reminder.</p></section>
    {error && <p role="alert" className="form-error">{error}</p>}<div role="status" className="feedback">{message}</div><div className="form-actions"><button className="button" type="submit" disabled={!dirty}>Save settings</button><button className="button secondary" type="button" disabled={!dirty} onClick={()=>{setDraft(structuredClone(settings));setError('');setMessage('Unsaved changes discarded.');}}>Discard changes</button>{dirty && <span className="muted">Unsaved changes</span>}</div></form><p className="settings-note">Your name and email live on <a className="text-link" href="#/profile">Profile →</a></p></>;
}
